networks:
  wooriga-network:
    driver: bridge

services:
  wooriga-app:
    image: ljyeon12/wooriga-be_wooriga-app:latest
    container_name: wooriga-app
    ports:
      - "8081:8080"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: wooriga-nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wooriga-app
volumes:
  db_data: