networks:
  wooriga-network:
    driver: bridge

services:
  wooriga-app:
    image: ljyeon12/wooriga-be_wooriga-app:latest
    container_name: wooriga-app
    ports:
      - "8081:8080"
    env_file:
      - .env

volumes:
  db_data: